# Generated by Django 4.2.6 on 2023-12-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reports", name="role_action",),
        migrations.AddField(
            model_name="reports",
            name="report_action",
            field=models.BooleanField(default=False),
        ),
    ]
