# Generated by Django 4.2.5 on 2023-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_reports_role_action_reports_report_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="evidences",
            field=models.ImageField(
                default="../frontend/images/A.png", upload_to="../WebsiteFiles"
            ),
        ),
    ]
