# Generated by Django 4.2.6 on 2023-12-23 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_reports_evidences"),
    ]

    operations = [
        migrations.RemoveField(model_name="reports", name="evidences",),
        migrations.AlterField(
            model_name="reports",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
