# Generated by Django 4.2.5 on 2023-12-24 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_remove_reports_evidences_alter_reports_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
