# Generated by Django 4.2.5 on 2023-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_reports_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="report_action",
            field=models.CharField(max_length=255),
        ),
    ]
