# Generated by Django 4.2.5 on 2023-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicename", models.CharField(max_length=255)),
                ("servicetarget", models.CharField(max_length=255)),
                ("servicedesc", models.TextField()),
                ("serviceprice", models.IntegerField(default=None)),
            ],
        ),
    ]
