# Generated by Django 4.2.5 on 2023-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_serviceuse_assignedemployees"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelist",
            name="status",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
