# Generated by Django 4.2.5 on 2023-12-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_servicelist_serviceavailable"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuse",
            name="servicevalue",
            field=models.IntegerField(default=None),
        ),
    ]
