# Generated by Django 4.2.5 on 2023-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_serviceuse_servicevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuse",
            name="totalprice",
            field=models.IntegerField(default=None),
        ),
    ]
