# Generated by Django 4.2.5 on 2023-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_serviceuse_totalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuse",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
