# Generated by Django 4.2.5 on 2023-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_serviceuse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuse",
            name="approved_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
