# Generated by Django 4.2.5 on 2023-12-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_serviceuse_approved_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviceuse", name="service_id",),
    ]
