# Generated by Django 4.2.5 on 2023-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_remove_serviceuse_service_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuse", name="approved_date", field=models.DateTimeField(),
        ),
    ]
