# Generated by Django 4.2.5 on 2023-12-27 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_alter_serviceuse_approved_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviceuse", name="assigned",),
        migrations.AlterField(
            model_name="serviceuse",
            name="approved_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
