# Generated by Django 4.2.5 on 2023-12-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_remove_serviceuse_services_serviceuse_services"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviceuse", name="services",),
        migrations.AddField(
            model_name="serviceuse",
            name="services",
            field=models.ManyToManyField(to="services.servicelist"),
        ),
    ]
