# Generated by Django 4.2.5 on 2023-12-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_remove_serviceuse_services_serviceuse_services"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviceuse", name="services",),
        migrations.AddField(
            model_name="serviceuse",
            name="services",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.servicelist",
            ),
            preserve_default=False,
        ),
    ]
