# Generated by Django 4.2.5 on 2023-12-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_remove_serviceuse_services_serviceuse_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuse",
            name="servicelocation",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
