# Generated by Django 4.2.5 on 2023-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_serviceuse_servicelocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedemployees",
            name="work_status",
            field=models.CharField(default="Free For Work", max_length=255),
        ),
    ]
