# Generated by Django 4.2.5 on 2023-12-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_assignedemployees_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedemployees",
            name="service_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.serviceuse",
            ),
        ),
    ]
