# Generated by Django 4.2.5 on 2024-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_assignedemployees_service_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuse",
            name="endHour",
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name="serviceuse",
            name="startHour",
            field=models.TimeField(default=None),
        ),
    ]
