# Generated by Django 4.2.5 on 2024-01-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_serviceuse_endhour_serviceuse_starthour"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelist",
            name="required_caliber",
            field=models.CharField(default="Bronze", max_length=255),
        ),
    ]
