# Generated by Django 4.2.5 on 2024-02-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_servicelist_required_caliber"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviceuse", name="endHour",),
    ]
