# Generated by Django 4.2.5 on 2024-02-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_remove_serviceuse_endhour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuse",
            name="services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.servicelist"
            ),
        ),
    ]
