# Generated by Django 4.2.5 on 2023-12-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0004_remove_users_fileupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.CharField(max_length=255, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                ("created_date", models.DateField()),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Pending", "Pending"),
                            ("Terminated", "Terminated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_type", models.CharField(max_length=255)),
                ("renewal_date", models.DateField()),
                ("contract_duration", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.users"
                    ),
                ),
            ],
        ),
    ]
