# Generated by Django 4.2.5 on 2023-12-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contractreview", "0002_alter_contract_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract", name="client_name",),
        migrations.RemoveField(model_name="contract", name="contract_type",),
    ]
