# Generated by Django 4.2.5 on 2023-12-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractreview", "0003_remove_contract_client_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Terminated", "Terminated"),
                ],
                max_length=20,
            ),
        ),
    ]
