# Generated by Django 4.2.5 on 2023-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractreview", "0006_contract_contract_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Terminated", "Terminated")],
                max_length=20,
            ),
        ),
    ]
