# Generated by Django 4.2.5 on 2024-01-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contractreview", "0007_alter_contract_contract_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="contract", name="contract_duration",),
    ]
