# Generated by Django 4.2.5 on 2024-02-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_notification"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="read",),
    ]
