# Generated by Django 4.2.5 on 2024-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0003_remove_notification_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
