# Generated by Django 4.2.5 on 2024-01-01 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_assignedemployees_service_request"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="contract",),
        migrations.AddField(
            model_name="payment",
            name="service_use",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.serviceuse",
            ),
        ),
    ]
