# Generated by Django 4.2.5 on 2024-01-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_remove_payment_contract_payment_service_use"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="payment_status",),
    ]
