# Generated by Django 4.2.5 on 2024-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_payment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_approval",
            field=models.BooleanField(default=False),
        ),
    ]
