# Generated by Django 4.2.5 on 2024-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_payment_payment_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_approval",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
