# Generated by Django 4.2.5 on 2024-01-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_assignedemployees_service_request"),
        ("payment", "0005_alter_payment_payment_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="service_use",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="services.serviceuse",
            ),
        ),
    ]
