# Generated by Django 4.2.5 on 2024-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
