# Generated by Django 4.2.5 on 2024-01-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0008_subscription_transaction_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caliber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caliber_level",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="bronze",
                        max_length=255,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=17000, max_digits=10),
                ),
                ("last_paid", models.DateField(blank=True, default=None)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_caliber",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ratings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_caliber_rating",
                        to="ratings.rating",
                    ),
                ),
            ],
        ),
    ]
