# Generated by Django 4.2.5 on 2024-01-08 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_caliber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caliber",
            name="last_paid",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
