# Generated by Django 4.2.5 on 2024-01-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_caliber_last_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="caliber",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
