# Generated by Django 4.2.5 on 2024-01-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_caliber_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_date",
            field=models.DateField(default=None),
        ),
    ]
