# Generated by Django 4.2.5 on 2024-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_subscription_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="caliber", name="desc", field=models.TextField(blank=True),
        ),
    ]
