# Generated by Django 4.2.5 on 2024-01-10 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_caliber_desc"),
    ]

    operations = [
        migrations.RemoveField(model_name="caliber", name="desc",),
        migrations.RemoveField(model_name="caliber", name="last_paid",),
        migrations.RemoveField(model_name="caliber", name="payment_status",),
        migrations.RemoveField(model_name="caliber", name="salary",),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(default=datetime.date.today)),
                ("description", models.TextField(blank=True)),
                (
                    "caliber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.caliber",
                    ),
                ),
            ],
        ),
    ]
