# Generated by Django 4.2.5 on 2024-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0016_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="refund_status",
            field=models.CharField(default="Pending", max_length=255),
        ),
        migrations.AddField(
            model_name="refund",
            name="service_name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
