# Generated by Django 4.2.5 on 2024-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_alter_refund_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="salary_book",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
