# Generated by Django 4.2.5 on 2024-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0020_alter_salary_amount_alter_salary_salary_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salary",
            name="salary_book",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
