# Generated by Django 4.2.5 on 2024-02-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0021_alter_salary_amount_alter_salary_salary_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary", old_name="payment_date", new_name="action_date",
        ),
    ]
