# Generated by Django 4.2.5 on 2023-12-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_users_delete_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="fileupload",),
    ]
