# Generated by Django 4.2.5 on 2023-12-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customtoken"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtoken", name="expires",),
    ]
