# Generated by Django 4.2.5 on 2023-12-21 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_customtoken_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
