# Generated by Django 4.2.5 on 2023-12-21 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_users_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtoken",
            name="expiration",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
