# Generated by Django 4.2.5 on 2023-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_customtoken_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="otp",
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
