# Generated by Django 4.2.5 on 2023-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_users_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="otp", field=models.IntegerField(max_length=4),
        ),
    ]
