# Generated by Django 4.2.5 on 2023-12-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_users_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="otp", field=models.IntegerField(),
        ),
    ]
