# Generated by Django 4.2.5 on 2023-12-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_users_otp"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="otp",),
    ]
