# Generated by Django 4.2.5 on 2023-12-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_users_is_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="users", name="contact", field=models.IntegerField(default=None),
        ),
    ]
