# Generated by Django 4.2.5 on 2023-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_users_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="contact", field=models.CharField(max_length=255),
        ),
    ]
