# Generated by Django 4.2.5 on 2023-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_users_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="otp", field=models.CharField(max_length=255),
        ),
    ]
