# Generated by Django 4.2.5 on 2024-01-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_users_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profilepic",
            field=models.ImageField(
                default="../WebsiteFiles/UserProfile/A.png",
                upload_to="../WebsiteFiles/UserProfile",
            ),
        ),
    ]
