# Generated by Django 4.2.5 on 2024-01-03 07:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_users_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profilepic",
            field=models.ImageField(
                default=app.models.default_profilepic_path,
                upload_to="WebsiteFiles/UserProfile",
            ),
        ),
    ]
