# Generated by Django 4.2.5 on 2024-01-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_users_profilepic"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="profilepic",),
    ]
