# Generated by Django 4.2.5 on 2024-01-03 13:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_users_profilepic"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profilepic",
            field=models.ImageField(
                default="WebsiteFiles/UserProfile/A.png",
                upload_to=app.models.default_profilepic_path,
            ),
        ),
    ]
