# Generated by Django 4.2.5 on 2024-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_announcements"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="citizenship_image",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="users",
            name="work_cv",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
    ]
