# Generated by Django 4.2.5 on 2024-01-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_users_citizenship_image_users_work_cv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="citizenship_image",
            new_name="citizenship_back",
        ),
        migrations.AddField(
            model_name="users",
            name="citizenship_front",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
    ]
