# Generated by Django 4.2.5 on 2024-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_rename_citizenship_image_users_citizenship_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="work_cv",
            field=models.FileField(blank=True, default=None, upload_to=""),
        ),
    ]
