# Generated by Django 4.2.5 on 2024-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_users_work_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profilepic",
            field=models.ImageField(default="A.png", upload_to=""),
        ),
    ]
