# Generated by Django 4.2.5 on 2024-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_users_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profilepic",
            field=models.ImageField(
                default="WebsiteFiles/UserProfile/A.png", upload_to=""
            ),
        ),
    ]
