# Generated by Django 4.2.5 on 2024-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_users_profilepic"),
    ]

    operations = [
        migrations.AddField(
            model_name="users", name="is_otp", field=models.BooleanField(default=False),
        ),
    ]
